### ISSUE TITLE
Show detailed information for subscriptions that customer has been assigned

### ISSUE THREAD

**Issue by itma** [blakeyman/bbradmin#1]
The publication list displayed shows ALL publications and which subscriptions the customer has been
assigned. For each subscription though we would also need to see the following (as per the database
schema).

Find more in the attachement.
[requirements v1.pdf](https://github.com/blakeyman/bbradmin/files/217003/requirements.v1.pdf)

**Comment by blakeyman** [comment]
Currently it only displays a subscription (name) but for each subscription we _additionally_ need to see

- number of copies

- complimentary

- different shipping address

**Comment by blakeyman** [comment]
and use v1.1 of requirements ;)

**Comment by itma** [comment]
Thanks for the reminder! :)

**Comment by itma** [comment]
The issue is (almost) ready to test. One thing is missed - grouping the subscriptions by the year. I will add it a little bit later.

**Comment by blakeyman** [comment]
So far everything looks amazing!!!!
